code-of-conduct.md

Added code of conduct for the Kubesimplify website repo.

Added Code of conduct

---

src/theme/Navbar/index.js

Docusaurus provides a way to customize the default components like Navbar, footer etc. We use `npm run swizzle @docusaurus/theme-classic` command for this. What it does if we select navbar or footer is it creates a new folder inside theme that has another folder for navbar or footer which we can customize according to our use.
Bhavya took the task to create Navbar for the website and as in her device the above mentioned command is not working due to some bug we didn't want to slow down our pace hence in order to help her creating this PR 
cc @anubha-v-ardhan @verma-kunal

[URGENT] added a Navbar folder 

---

README.md

Readme.md created

---

src/components/HomepageFeatures/index.js
src/components/HomepageFeatures/styles.module.css
src/theme/Navbar/styles.module.css

[x] - Fixed About tab margin in navbar and added cursor to all

Fixed About tab margin and newsletter button in navbar and added cursor to all 

---

src/components/HomepageFeatures/index.js
src/components/HomepageFeatures/styles.module.css

[x] - Hover effect added and cursor changed to pointer

Start learning button upgraded 2.0

---

src/theme/Navbar/styles.module.css

fixed all alignments of navbar buttons 2.0

---

.github/auto_assign.yml
.github/workflows/pull-request.yml

Created a gh actions workflow for auto-assiging @AvineshTripathi as a reviewer to any PR that is made to this repo!

Add: Auto-assign workflow

---

src/pages/about.js
src/theme/Navbar/index.js

Signed-off-by: Dipankar Das <dipsonu10@hotmail.com>
[ ] - Not correct; marked as **not** done

Setup for the About Page

---

CONTRIBUTION.md

Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Added a CONTRIBUTION.md file, which explains:
- Add the contributing.md file explaining how to clone the repo and get started with contributing.
- What are the requirements one should have before cloning the repo?
- Mention how to propose a feature request?
- How to create a pull request?
- `Closes #58` [issue. #58](https://github.com/kubesimplify/website/issues/58#issue-1253694737)

Adding Contribution.md file 

---

package-lock.json
src/theme/Navbar/index.js
src/theme/Navbar/styles.module.css

Feat: Removing the underline effect at the about button Closes#101

---

src/theme/Navbar/index.js

- hyper link of workshop page add
#110

hyper link of workshop page add

---

src/components/HomepageFeatures/index.js

With the addition of this feature now folks can add email and get subscribed to the Revue newsletter

added newsletter subscribe feature

---

src/theme/NotFound.js

cc @bhavyastar you can now start working on 404 now

added 404 page folder

---

src/theme/Footer/styles.module.css

footer css fix

---

src/theme/Navbar/styles.module.css

added hover effect on navbar buttons

---

package-lock.json
package.json
src/theme/Navbar/index.js
src/theme/Navbar/styles.module.css

made navbar responsive

---

src/theme/Footer/index.js
src/theme/Footer/styles.module.css

made footer responsive

---

src/components/HomepageFeatures/index.js
src/components/HomepageFeatures/styles.module.css

made hompage responsive

---

src/components/ambassadors/Benifits.js
src/components/ambassadors/style.module.css
src/pages/ambassadors.js

made ambassador page responsive

---

src/components/HomepageFeatures/index.js
src/components/HomepageFeatures/styles.module.css

fixed home bug

---

src/components/HomepageFeatures/styles.module.css

fixed home alignment

---

src/components/HomepageFeatures/index.js
src/components/HomepageFeatures/styles.module.css
src/theme/Footer/index.js
src/theme/Footer/styles.module.css
src/theme/Navbar/index.js

All missing link is attached by this fix

fix: All missing link is attached

---

CONTRIBUTION.md

Docusaurus link was not added in the mentioned Style guide
Add the link to the website Docusaurus 
[Screencast from 03-07-22 02:42:01 PM IST.webm](https://user-images.githubusercontent.com/33636054/177033334-fb157829-9a59-401a-802d-21a65337d023.webm)
Can I See the website Layout?

added Docusaurus link

---

src/components/HomepageFeatures/styles.module.css
src/theme/Footer/styles.module.css

Hover effect added on all buttons in homepage.

Hover effect added on all buttons

---

README.md

**Note for Reviewers:-**
```text
Sorry I have not created an issue for this 😢 
```

Typos `kubesimplfy's` fixed in README.md

---

src/components/HomepageFeatures/styles.module.css
src/theme/Footer/index.js
src/theme/Footer/styles.module.css
src/theme/Navbar/styles.module.css

fixes button which are not aligned in `homepage`, `navbar`, `footer`

fixed button

---

src/theme/Footer/styles.module.css

margin-bottom added

---

src/theme/Footer/index.js

#172 discord invite link is expired 
I have changed the expired invite discord link to a new invite discord link (which can never expire).

discord link changed

---

src/theme/Footer/index.js

Modified mail ID

---

src/components/HomepageFeatures/index.js
src/theme/Footer/index.js
src/theme/Navbar/index.js

Urgent link fix after domain name change

fixed links

---

src/theme/NotFound.js

redirecting temporary solution
it is working fine on my device

redirecting temporary solution

---

src/theme/NotFound.js

slice method

---

src/components/ambassadors/style.module.css
src/pages/ambassadors.js

https://github.com/kubesimplify/website/issues/166
The website is now according to the design and is fully responsive.

Margin of ambassador page fixed and made responsive

---

src/components/ambassadors/style.module.css
src/pages/ambassadors.js

Reverts kubesimplify/website#182
ambassador page breaks due to the merge discussed in #181

Revert "Margin of ambassador page fixed and made responsive"

---

src/components/HomepageFeatures/index.js

Discord link redirecting issue is resolved!

Fix discord link redirecting issue

---

src/theme/Footer/index.js

Fixed Typo in the footer

---

README.md

Updated broken link of Contibution.md from readme file to CONTRIBUTING.md

Fix: broken link CONTRIBUTING.md

---

src/components/ambassadors/FAQs.js

Fixed typos on the Ambassadors FAQ section

Fixed typos on the ambassador FAQ

---

src/data/data.js
src/pages/workshops.js
src/theme/Navbar/index.js
src/theme/NotFound.js

Hey @verma-kunal I have changed the Live- workshop url from 
`kubesimplify.com/live-workshops` from `kubesimplify.com/workshops`
I have updated the date of two cards also.

changed workshop url

---

src/components/HomepageFeatures/styles.module.css

Fix: horizontal line of  Learn cloud native text of homepage.

---

src/components/HomepageFeatures/index.js
src/components/team/Team.js
src/components/team/styles.module.css
src/data/data.js

I have updated the kubesimplify ambassadors photo and their social links.

updated ambassadors photo and their social links

---

src/components/liveworkshop/styles.module.css

fixed card height

---

src/components/HomepageFeatures/index.js

fixed broken discord link at start-learning on home page

---

src/components/HomepageFeatures/index.js

Update discord invite  link

---

src/data/data.js

Added new ambassadors.
@AvineshTripathi  Can you please Merge the PR?

Added new ambassadors

---

src/theme/Footer/styles.module.css

Email logo size fixed
issue: #220

email logo size fixed

---

src/theme/NotFound.js

Added a new book redirect
kubesimplify.com/book -> https://saiyampathak.gumroad.com/l/visualbook

added book redirect

---

src/theme/Footer/index.js

Copyright section update for 2023
close: #227

Copyright section update

---

package-lock.json
src/components/Aboutpage/Founder.js
src/components/Aboutpage/Mission.js
src/components/HomepageFeatures/index.js
src/components/PDF.js
src/components/liveworkshop/LiveWorkshop.js
src/pages/about.js
src/pages/ambassadors.js
src/pages/index.js
src/theme/Navbar/index.js

- Removed Kubsimply Ambassadors page and added Kubesimply Hindi in Navbar Menu
- Change the title of the main section of kubesimply from "On a mission to teach cloud native to everyone" to "On a mission to teach cloud native, AI and Wasm to everyone"
- Replace the workshop image in workshop section of main page to workshop youtube video 
- Remove "Be a Part of kubsimplify Ambassador" Section in main page
- Remove Kubsimplify Ambassador Members Section in about page
- Added personal social handles of saiyam in teh founder section 
- Embed "Collabrate with Us"  PDF section before Footer 
- Changes the decription of the founder section

rewamp website
